=== api-evangelist/amazon-iot-device-management/json-schema/iot-device-management-get-policy-version-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-iot-device-management/refs/heads/main/json-schema/iot-device-management-get-policy-version-response-schema.json",
  "title": "GetPolicyVersionResponse",
  "description": "The output from the GetPolicyVersion operation.",
  "type": "object",
  "properties": {
    "policyArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PolicyArn"
        },
        {
          "description": "The policy ARN."
        }
      ]
    },
    "policyName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PolicyName"
        },
        {
          "description": "The policy name."
        }
      ]
    },
    "policyDocument": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PolicyDocument"
        },
        {
          "description": "The JSON document that describes the policy."
        }
      ]
    },
    "policyVersionId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PolicyVersionId"
        },
        {
          "description": "The policy version ID."
        }
      ]
    },
    "isDefaultVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IsDefaultVersion"
        },
        {
          "description": "Specifies whether the policy version is the default."
        }
      ]
    },
    "creationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateType"
        },
        {
          "description": "The date the policy was created."
        }
      ]
    },
    "lastModifiedDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DateType"
        },
        {
          "description": "The date the policy was last modified."
        }
      ]
    },
    "generationId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenerationId"
        },
        {
          "description": "The generation ID of the policy version."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-iot-device-management/examples/iot-device-management-get-policy-version-response-example.json
{
  "policyArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "policyName": "example-resource",
  "policyDocument": "example-value",
  "policyVersionId": "id-abc123",
  "isDefaultVersion": "example-value",
  "creationDate": "example-value",
  "lastModifiedDate": "example-value",
  "generationId": "id-abc123"
}
